### ISSUE TITLE
Want to collaborate?

### ISSUE THREAD

**Issue by cweagans** [mkusher/padawan.php#1]
Hey @mkusher, I started working on a similar project a couple months ago: https://github.com/cweagans/theforce

Want to work together? I'd love to help on this!

**Comment by mkusher** [comment]
@cweagans hi! I saw your project few weeks ago, when I've already created indexer and $this completion in mine. Saying honestly your project's name inspired to call it "padawan" :) 
As I understand our projects are slightly different: my project based on "Index cache". Of course I'd like to join our "forces". 
Can you describe current state of your project?

**Comment by cweagans** [comment]
:)

Right now, my project can recursively iterate through all the files in a directory. Every file that matches a configurable extension (defaults to .php) will be parsed and symbol information will be stored in the symbol table. Right now, the symbol table is not really very useful. The only thing that you can actually get out of the server are global function names (no namespace support).

Your project looks like it has a much nicer architecture, so it might be wise to just scrap my project and continue with yours. The last thing I was doing on mine was to think through some tests of what kind of completions should actually be possible. Might be a good idea to start with those kinds of tests here, and if you want, I can focus my time on doing that.

**Comment by mkusher** [comment]
@cweagans got it. So, my project already can complete `$this` and method arguments, but it have been done as pof, so now I'm writing tests for [`ContextResolver`](https://github.com/mkusher/padawan.php/blob/master/specs/completer/resolver/ContextResolver.spec.php), `Scope processor` and refactoring context-scope structure. [There are also namespaces, classes' and interfaces' names completion](https://github.com/mkusher/padawan.php/tree/master/src/Complete/Completer).
I also have simple hardcoded [YCMD client](https://gist.github.com/mkusher/e1552b55fa535e5bdc27)(you should manually start padawan's server) but I don't know how I can add YCMD client without modifying ycmd sources.
There are some problems to be solved:
1. Completion doesn't work with new files
2. There are no index update on new vendor files
3. There is no tools for plugins, but I have some ideas about it
4. There is no expression(For example `$var->method()->param`) type detection, but I'm working on it
5. Completion services structure sucks, classes' names are unclear and classes inheritance in this part are also terrible. And I'm also working on it :)

Talking about tests, what kind of tests do you mean? There are some unit-tests written with peridot framework(`/specs` folder), but I also want to add [behat full system tests](https://github.com/mkusher/padawan.php/blob/master/features/indexing.feature)

**Comment by mkusher** [comment]
@cweagans I've made short video that shows current state of the project: https://youtu.be/Y54P2N1T6-I

**Comment by mkusher** [comment]
@cweagans and now I've added [Vim client](https://github.com/mkusher/padawan.vim)
