### ISSUE TITLE
`update` command cause `File not found` error.

### ISSUE THREAD

**Issue by musou1500** [mkusher/padawan.php#104]
If working directory of `padawan-server` and project root directory is not same, `update` command cause `File not found` error.

To reproduce it,
1. exec `padawan-server` in directory which is not project root.
2. send `update` command to server with correct `path` parameter.
3. error occurs. `padawan-server` will show error log.

thanks.

**Comment by halftan** [comment]
Will fix in #103

**Comment by musou1500** [comment]
@halftan thanks.

**Comment by phux** [comment]
This can be closed, right?
