### ISSUE TITLE
Use a folder as reference for everything

### ISSUE THREAD

**Issue by Mte90** [mkusher/padawan.php#113]
It is better to explain with an user case:
I develop with PHP only for WordPress, so for me is useful to have everywhere hints about the code base of this project.
So I am wondering if it is possible to have an index shared with everything inside my editor (VIM) and not only for project where I am working.
There is a parameter to define this behaviour?

**Comment by Mte90** [comment]
I think that adding a path there is the solution https://github.com/padawan-php/padawan.php/blob/master/src/Padawan/Command/GenerateCommand.php#L42

**Comment by Mte90** [comment]
Also adding a parameter con `padawan generate` for a path can be used to specify a project folder and not only the folder in use.

**Comment by mkusher** [comment]
I think I didn't get it. If nothing passed to `padawan generate`, than it will use current working directory as project root, isn't it the behavior you want?

**Comment by Mte90** [comment]
As example I am modifying a file on `/path/of/folder/with/nested/code/and/stuff.php`, I want that padawan generate from `/path/of/folder/` and not `/path/of/folder/with/nested/code/and/`.
How I can do that with padawan? Maybe I missed something.

**Comment by mkusher** [comment]
`$ padawan generate --path /path/of/folder` or `$ cd /path/of/folder && padawan generate`

**Comment by Mte90** [comment]
Where padawan will generate the index? in what folder?
Because as I understood will search the index in the folder where I am editing but in my case that folder is a parent one.
So the best option seems to execute the generation with a path inside the folder where there are the files that I am editing.

My issue is that I want that index is shared with all the php project that I have to avoid to generate for all of them.

**Comment by mkusher** [comment]
> Where padawan will generate the index? in what folder?

in both of my examples padawan will generate index in `/path/of/folder`

**Comment by Mte90** [comment]
Ok So I have to execute that on the folder where I am working?

**Comment by Mte90** [comment]
Seems that `--path` command doesn't exist in that format but only `path` in any case wroked.
I am wondering if there is a parameter to exclude folders to scan.
In that way I can integrate the generate with https://github.com/phpro/grumphp

**Comment by Mte90** [comment]
This is the command that I am using right know: ``/opt/padawan/padawan.php/bin/padawan generate path``

**Comment by Mte90** [comment]
I was thinking but padawan look on parents folder for `.padawan` folder?

**Comment by Mte90** [comment]
Ok padawan check the parent folder so I put the index on the main folder of wordpress and I can access to everything :-)
