### ISSUE TITLE
FQCN.php doesn't check if countable

### ISSUE THREAD

**Issue by ProfessorChill** [mkusher/padawan.php#115]
Hello! Firstly, sorry. I have never done a commit to another persons project before, so I will just tell you what the issue is here and hopefully that's can fix it!

There is an issue
```
Warning: count(): Parameter must be an array or an object that implements Countable in /home/lunakiraizarus/.config/composer/vendor/mkusher/padawan/src/Padawan/Domain/Project/FQCN.php on line 19
```

On line 19 of FQCN.php we can simply add
```
if (is_array($this->parts) || $this->parts instanceof Countable) {
     // Rest of code
}
```

And it fixes the error message, the error message also causes a large amount of memory to be used up. I think it would be called a memory leak?

I am using Padawan with composer under dev-master so I'm sorry if this is already fixed.

**Comment by halftan** [comment]
I think it's better to resolve the cause than suppressing the warning.

 `$this->parts` needs to be a valid array, but I guess there's something wrong when initializing this field.

Maybe we can change this line https://github.com/padawan-php/padawan.php/blob/master/src/Padawan/Domain/Project/FQN.php#L12

`elseif (!is_array($namespace)) {`

to

`elseif (is_string($namespace)) {`

**Comment by halftan** [comment]
Oh, btw, @ProfessorChill: PR is always welcomed. Please feel free to submit one if you think it's necessary. It's open source & github, man 😄

**Comment by Mte90** [comment]
Same error, it is open source but the project have 11 pr in queue so if is not active is better to patch to use it locally for the moment :-)
