### ISSUE TITLE
Function suggestions should append brace

### ISSUE THREAD

**Issue by msjyoo** [mkusher/padawan.php#19]
Hello,

When autocompleting functions, is it possible to have an option where braces are appended?

e.g. `function(` is inserted instead of `function`

**Comment by mkusher** [comment]
It could be done here https://github.com/mkusher/padawan.php/blob/master/src/Complete/Completer/ObjectCompleter.php#L67
but I'm not sure whether it should be done on server(padawan.php) or client(vim, sublime etc.)

**Comment by msjyoo** [comment]
@mkusher It'd be great if it could be done on the client, and maybe there could be an option to set the setting? But I couldn't find out whether Padawan.php sends signatures (variable, function, constant etc.) to the client.

**Comment by mkusher** [comment]
@sekjun9878 for variables and properties `menu` will contain type or FQCN and for methods and function it will be signature(e.g. `(array $needle, string $search): mixed`)

**Comment by msjyoo** [comment]
If this functionality is implemented, in vim, `autocmd CompleteDone * if getline('.')[col('.')-2] == "(" | execute "normal i)" | endif` can achieve brace auto-completion similar to how PHPStorm works.

**Comment by mkusher** [comment]
Closing, cause should be done on client side
