### ISSUE TITLE
how work the server?

### ISSUE THREAD

**Issue by Azakur4** [mkusher/padawan.php#2]
Im building a package that use this server to get autocompletion for php, but until now i generate the index file (.padawan/project), after this point im a little lose cuz i start the padawan server but i don't know to what url make the query for the autocompletions.

I know that in the realm u have linked a vim plugin and until i see u call to a complete method passing 4 parameters, im trying to do that with a tester app to http request and restful api but i don't get any completion passing the 4 parameters.

Exists some doc about how the server use this 4 parameters or if need something more?

**Comment by mkusher** [comment]
@Azakur4 hi!
First of all, have a look at this python client https://gist.github.com/mkusher/43bcff85d5e2f3ec3c55 and angular.js client http://mkusher.name/padawan/app.js
As of now there are 4 urls(You can see them [here](https://github.com/mkusher/padawan.php/blob/master/src/Router.php)):
- complete
- update
- generate
- save

Talking about /complete you've just need to send in request uri(query string):

``` python
        params = {
            'filepath': filepath.replace(curPath, ""),
            'line': request_data['line_num'],
            'column': request_data['column_num'],
            'path': curPath
        }
```

and file contents in request body

**Comment by Azakur4** [comment]
Hi man, yeah i figure out, but until now was very hard understand the server. Do you have a place that we can chat need some advices if u have a time to help me.

**Comment by mkusher** [comment]
I think skype chat is the right place, my nickname is `mkusher`

**Comment by Azakur4** [comment]
Added my nickname is Azakur4, please accept

**Comment by mkusher** [comment]
Documentation can be found here https://github.com/mkusher/padawan.php/wiki/Editor-plugins
