### ISSUE TITLE
Namespace completion

### ISSUE THREAD

**Issue by MichaelMackus** [mkusher/padawan.php#24]
In the README I see namespace completion which looks to be working in Sublime. However, in the VIM plugin it doesn't seem to work properly. If I type

``` php
use 
```

Then `<C-x><C-o>` (trigger omnicomplete) I get an error `Pattern not found`. Same if I input text first like

``` php
use Symf
```

Just wondering if this a VIM implementation issue, or issue with the padawan server? Also, I'm on commit hash be0cd81

Cheers

**Comment by mkusher** [comment]
looks strange, I've just tried it in my neovim and it worked as expected. So, if sublime configured to work with composer global padawan(which is done by default) and it works well, then I can say, that the issue is in the padawan.vim.
Can you share your `vimrc` or `init.vim`?

**Comment by MichaelMackus** [comment]
Hmm, ok. Its not too big of a deal, as I'm currently using spacemacs/emacs and am considering creating a completion plugin for it (instead of using ac-php which is not as good as padawan IMO, especially if namespace completion _is_ supported).

[Here's](https://github.com/MichaelMackus/dotfiles/blob/master/vim/vimrc) a link to my vimrc if helpful

**Comment by MichaelMackus** [comment]
@mkusher hmm I just tried neovim and namespace completion isn't working for me there either :(

Same vimrc, using `<C-x><C-o>` after `use Symf` returns "Error occured timed out" in neovim status line.

Here's the padawan server output:

``` bash
POST /complete
[2016-02-18 12:30:25] completer.DEBUG: 0.00014400482177734 seconds for ast processing [] []
[2016-02-18 12:30:25] completer.DEBUG: Found token '' with type 16 [] []
[2016-02-18 12:30:26] completer.DEBUG: 0.58465218544006 seconds for entries generation [] []
Response time: 0.92782807350159
```

I've verified my padawan.vim plugin is up to date, as well as padawan.php and the problem persists. I would love to get this working in either vim/neovim.

As a side note, neovim is looking really nice! Crazy fast startup as well. All the other padawan features seem to work fine.

**Comment by mkusher** [comment]
@MichaelMackus "time out" can occur in case of a big project, can you try entering something like 

``` php
use Symfony\<C-x><C-o> 
```

I think you should get completion in this situation.

> (instead of using ac-php which is not as good as padawan IMO, especially if namespace completion is supported).

thanks for a good words :)

**Comment by MichaelMackus** [comment]
Still not working for me unfortunately :(

It is definitely a large(r) project, so that could be where these errors are coming from. Fairly standard Symfony core though, so not sure why it won't complete Symfony use statements.

With `use Symfony\<C-x><c-o>` I get the same timeout error, but I do get some more output from padawan-server:

``` bash
POST /complete
[2016-02-18 14:11:30] completer.DEBUG: 0.00015711784362793 seconds for ast processing [] []
[2016-02-18 14:11:30] completer.DEBUG: Found token ' Symfony\' with type 16 [] []
[2016-02-18 14:11:31] completer.DEBUG: 1.6260840892792 seconds for entries generation [] []
Response time: 2.3288650512695
```

EDIT: I noticed there was a space in the "Found token" line, so I tried completing without the "use " part (just at start of line `Symfony\<C-x><C-o>`) and get this output:

``` bash
POST /complete
[2016-02-18 14:13:37] completer.DEBUG: 0.00025200843811035 seconds for ast processing [] []
[2016-02-18 14:13:37] completer.DEBUG: Found token 'Symfony\' with type 4097 [] []
[2016-02-18 14:13:37] completer.DEBUG: 0.0026180744171143 seconds for entries generation [] []
Response time: 0.0041141510009766
```

Still no completion popup unfortunately

**Comment by mkusher** [comment]
@MichaelMackus ok, try `<C-x><C-o>` multiple times. First request takes long time, cause padawan.php have to load project cache and deserialize index

**Comment by MichaelMackus** [comment]
Unfortunately no matter how much times I try it doesn't seem to work with any namespace completion :(

Same error(s) continue. Interestingly, in the second case above, I don't get a timeout error, but do not get a completion popup.

Also, all the other padawan functions work fine within that buffer, so that makes me think padawan is already loaded & prepped.

**Comment by mkusher** [comment]
@MichaelMackus without use it won't work, cause it is invalid token. Time out error can occur when the project is not ready or when there are too many items, so, try to use more specific namespace, like

``` php
use Symfony\Component\<C-x><C-o>
```

**Comment by MichaelMackus** [comment]
@mkusher still no cigar unfortunately

It might indeed just be a timeout issue, since I'm getting 1-5 second response time for all namespace completions, and much less than 1 second response time for all other completions.

Is there any way to increase timeout maybe?

**Comment by mkusher** [comment]
yeah, try setting 

``` vim
let g:padawan#timeout = 10
```

it will increase timeout to 10 seconds, just for test purpose

**Comment by MichaelMackus** [comment]
Yup, that seems to work! Takes a little while, but it does work with increased timeout.

**Comment by mkusher** [comment]
@MichaelMackus hmm, it's not very good to have such delay, but currently I'm not going to optimize it, so I think the issue is closed now
