### ISSUE TITLE
does not obey @property dockblock

### ISSUE THREAD

**Issue by mikk150** [mkusher/padawan.php#26]
padawan seems not to care about @property tag
(I think it doesn't care about @method tag too)

**Comment by mkusher** [comment]
@mikk150 that's true, currently padawan simply adds doc comment text to class, but do not process it.

https://github.com/mkusher/padawan.php/blob/master/src/Parser/ClassParser.php#L106

Not sure whether it is feature request or bug :)

**Comment by mikk150** [comment]
yes, it is a feature request. I think it is much needed, because at this point I can't use padawan(I am forced to use codeintel at this point)

Yii2 framework relies heavily on magic getters and setters and magic call functions, so there it is much needed

**Comment by mkusher** [comment]
@mikk150 will try to spend time on padawan next weekend, but if you have some free time you may try implement this feature. It might be faster, than waiting for me(sorry I'm too busy on my current project :( ).

**Comment by mikk150** [comment]
I'll see what I can do. I have done something like this with reflection-dockblock, it is really easy. But I have to figure out, how I can inject it in padawan

**Comment by mkusher** [comment]
@mikk150 padawan already parses doc-comment, but do not process it

**Comment by halftan** [comment]
It seems like this feature was implemented [here](https://github.com/padawan-php/padawan.php/blob/master/src/Padawan/Parser/CommentParser.php#L65)

closing this issue.

**Comment by mkusher** [comment]
@halftan should we have another one for `@method` block?

**Comment by halftan** [comment]
@mkusher yes, I'll implement this feature in the same PR
