### ISSUE TITLE
Itens than can be nice to have

### ISSUE THREAD

**Issue by Azakur4** [mkusher/padawan.php#3]
Well like i talk with u @mkusher i will put here some itens that can be nice to have in padawan.php
- Autocomplete for variables.
- Autocomplete for default keywords and functions for php
- The actual functionality only show autocomplete when the cursor is after the "->" symbol. i think this can be done in the client too, maybe the client can recognize the principal object a save the autocompletions.

For now is that i will go thinking in other staff and editing this issue to make this more elaborated.

**Comment by mkusher** [comment]
@Azakur4 first item is done, second one is moved to https://github.com/mkusher/padawan.php/issues/7
third one should be done on a client side

**Comment by Azakur4** [comment]
Nice work i will review that next week.
