### ISSUE TITLE
padawan crashes when processing a Symfony tests fixture.

### ISSUE THREAD

**Issue by Neopallium** [mkusher/padawan.php#34]
When generating the index for a new Laravel project the indexer Segfaults (php 5.6.20 Debian 8.4) while processing this Symfony test class.
https://github.com/symfony/var-dumper/blob/master/Tests/Fixtures/NotLoadableClass.php

It seems the issue is with the class extending itself:
`class NotLoadableClass extends NotLoadableClass
`

If I change one of the class names it will finish wihtout crashing.

I have also noticed that about 50Mbytes of memory is allocated while processing that class.  So maybe there is some reference loop.  The PHP process doesn't seem to hit the memory limit (padawan sets the limit to 2Gbytes), the whole process uses around 500Mbytes (199Mbytes reported in the log) when it crashes.

**Comment by mkusher** [comment]
Interesting issue. I guess indexer tries to get info about parent class and that why it fails.

**Comment by Neopallium** [comment]
I didn't realize that I was using an older version of the padawan server.  Attached is the output from the latest padawan-server.  It fails with a syntax error instead of a hard crash like before.  Is it possible to just ignore all PHP parsing errors?

[symfony_generate.txt](https://github.com/mkusher/padawan.php/files/253881/symfony_generate.txt)

**Comment by Neopallium** [comment]
I think this is really a duplicate of issue #32 , so I will close this issue.
