### ISSUE TITLE
Generated index is not saved if the ".padawan" folder doesn't exist.

### ISSUE THREAD

**Issue by Neopallium** [mkusher/padawan.php#36]
The sub-folder is not created before saving the index, so no ".padawan/project" file is created if the sub-folder doesn't exist.

**Comment by mkusher** [comment]
hm, looks like I've broken this in https://github.com/mkusher/padawan.php/commit/65bd91dba04296e8fe21c9a185c17882cca2fca5

**Comment by mkusher** [comment]
should be fixed in https://github.com/mkusher/padawan.php/commit/6816c3262314b57904ec31a1a427b656ffe73f8c
