### ISSUE TITLE
Upgrade to php-parser ~2

### ISSUE THREAD

**Issue by nesl247** [mkusher/padawan.php#40]
nikic/php-parser has had a ~2.0 release since December 2015. It adds support for PHP 7 amongst other things. It would be a good idea to upgrade.

I also can't use padawan at all until then as I already have something installed requiring 2.0.

**Comment by mkusher** [comment]
fixed in https://github.com/mkusher/padawan.php/commit/802b2cbb568008f9c2a5d5c2367e9547eabd1dea
