### ISSUE TITLE
Discoverability

### ISSUE THREAD

**Issue by greg0ire** [mkusher/padawan.php#50]
On my setup, typing just `bin/padawan` or `bin/padawan made-up` argument does nothing. I would expect that to give a list of possible commands / the help for padawan.

**Comment by greg0ire** [comment]
Looking at the code, I think having an `ErrorCommand` makes no sense, and an exception should be thrown instead. Also, how about symfony's Console component? It should make all this easy.

**Comment by greg0ire** [comment]
Apparently, the console component is already an implicit dependency of the project : 

```
  - Installing symfony/console (v2.8.8)
    Downloading: 100%   
```

**Comment by mkusher** [comment]
@greg0ire version in master does it

**Comment by greg0ire** [comment]
Oh… ooooh. I feel stupid right now. Closing, sorry.

**Comment by mkusher** [comment]
@greg0ire it's ok, cause there is still no stable release with this fix :(

**Comment by greg0ire** [comment]
May I ask, why don't you release more often ? The last release is almost one year old :confused:

**Comment by mkusher** [comment]
@greg0ire planned to much features to add :(

**Comment by greg0ire** [comment]
Feels very familiar :)
Do you have a moment to talk about our lords and saviours [time-based release](https://about.gitlab.com/2016/07/21/release-early-release-often/)? I think switching to that kind of release would spare you some stupid issues like this one, and to get earlier feedback on new things, while making upgrade less painful. The only drawback I can see is that it will force you to have higher version numbers quicker (think firefox 47), but I don't think anyone really cares about that, so please consider it.

**Comment by mkusher** [comment]
it's a good idea, I'll need to more accurately manage my time, so I'll have more time to spend on padawan
