### ISSUE TITLE
Class 'Padawan\Command\GenerateCommand' not found

### ISSUE THREAD

**Issue by MichaelMackus** [mkusher/padawan.php#51]
Maybe missing GenerateCommand.php file in git? Doesn't look like its in the Command directory at all, and its being referenced via Framework\Application\Cli.php on commit f030bea741aee44eea6f8eee7f9abce569056174

**Comment by mkusher** [comment]
hah, yeah, looks like missed it in git

**Comment by mkusher** [comment]
@MichaelMackus should be fixed in https://github.com/mkusher/padawan.php/commit/9a11001b536a8886e7fa6beeda460a8e253ca9dc
