### ISSUE TITLE
Doesn't work at all

### ISSUE THREAD

**Issue by golaod** [mkusher/padawan.php#56]
I wiped original message for this:
To make it work, I had to install EnvironmentSettings to add padawan to $PATH, because sublime python just didn't see my real env variables. Composer autoloader works. I commented out symfony class to reindex everything. I chose 'generate index' but still couldn't make it work, because in GetProjectRoot I had to return `sublime.active_window().extract_variables()['folder']` instead of current code. Then I fired 'start server' and I see process working and port reserved, but in sublime I see 'padawan.php' is not running.

It's was really hard way and it was for nothing. Any suggestions?

**Comment by mkusher** [comment]
@golaod hi, sorry for late reply. 
About env: I guess you're setting them in bashrc or zshrc, but it is better to do this in bash_profile, zprofile or so. 
Also thx for looking through the code, I'm not good at all in sublime plugin scripting, so there might be bugs. And I haven't tested padawan in sublime for a while, but there was no breaking changes... 
Can you try doing manual request like [here](https://github.com/mkusher/padawan.sublime/blob/master/padawan.py#L102)?

**Comment by mkusher** [comment]
Also can you manually run padawan-server(in terminal) and see whether it receives requests from sublime?

**Comment by mkusher** [comment]
@golaod hi, I've just updated https://github.com/mkusher/padawan.sublime so it should work, can you try it?

**Comment by mkusher** [comment]
if the issue is still valid, reopen it

**Comment by golaod** [comment]
Sorry for not responding, but I was sick.

Also I just tested it and it works :)

**Comment by mkusher** [comment]
@golaod that's great, thx! Hope you're well now :)
