### ISSUE TITLE
PHP Parse Error - unexpected 'loadRequestData'

### ISSUE THREAD

**Issue by GATDev** [mkusher/padawan.php#57]
Hi,

I'm trying to use Padawan for the first time but having issues with running the server. I'm using Neovim with the padawan.vim (with Symfony2 padawan plugin) and deoplete-padawan plugins. I can successfully generate an index for my composer project (both from within Neovim and from the command line) but when I try to use the autocompletion I get a 'Pattern not found' error along with a 'Padawan.php is not running' message in :messages. :PadawanStartServer doesn't have any effect in Neovim and at the command line, running padawan-server gives the following error:

PHP Parse error:  syntax error, unexpected 'loadRequestData' (T_STRING) in /Users/gary/.composer/vendor/mkusher/padawan/bin/padawan-server on line 51

Any ideas where I can start looking with this?

**Comment by mkusher** [comment]
@GATDev hello. Oh, looks like the php 5 bug. Try updating to php 7, if it's possible. I'll fix it asap

**Comment by GATDev** [comment]
@mkusher I'm afraid PHP7 isn't an option for this project (server limit of 5.6) but I really appreciate you getting back to me so quickly and I'll take a look at Padawan again once/if there's a 5 fix or if I have the opportunity to work on a 7 project.

**Comment by mkusher** [comment]
@GATDev can you try this branch https://github.com/mkusher/padawan.php/pull/58 ?

**Comment by mkusher** [comment]
unfortunately I've no tests for two files in bin, so they might have bugs :(
I've tried this branch in docker and it looks like everything is ok

**Comment by GATDev** [comment]
Thanks @mkusher, I'll give that branch a try this evening and report back

**Comment by GATDev** [comment]
Just tried this out now and all seems well. Thanks @mkusher!

**Comment by mkusher** [comment]
fixed in https://github.com/mkusher/padawan.php/commit/f666908d5ab76ec1068e95e3429af18674d2e58f
