### ISSUE TITLE
composer install fails

### ISSUE THREAD

**Issue by f0086** [mkusher/padawan.php#6]
- Installing zendframework/zend-stdlib (2.4.0)
  Cloning eab586f4c18af3fa63c977611939f1f4a3cf1030
  
  [RuntimeException]  
  Failed to clone git@github.com:zendframework/Component_ZendStdlib.git via git, https, ssh protocols, aborting.  
- git://github.com/zendframework/Component_ZendStdlib.git  
  Cloning into '/tmp/padawan.php/vendor/zendframework/zend-stdlib'...  
  fatal: remote error:  
    Repository not found.  
- https://github.com/zendframework/Component_ZendStdlib.git  
  Cloning into '/tmp/padawan.php/vendor/zendframework/zend-stdlib'...  
  remote: Invalid username or password.  
  fatal: Authentication failed for 'https://github.com/zendframework/Component_ZendStdlib.git/'  
- git@github.com:zendframework/Component_ZendStdlib.git  
  Cloning into '/tmp/padawan.php/vendor/zendframework/zend-stdlib'...  
  ERROR: Repository not found.  
  fatal: Could not read from remote repository.                                                                 
  
  Please make sure you have the correct access rights  
  and the repository exists.

**Comment by mkusher** [comment]
hi @f0086 
I thought there was an error in travis's mirrors, but it is not. Now it is fixed, so checkout latest master and run `composer install` again.

https://travis-ci.org/mkusher/padawan.php/jobs/72593936
