### ISSUE TITLE
Shouldn't bulit-ins get completed?

### ISSUE THREAD

**Issue by cprn** [mkusher/padawan.php#67]
Everything works okay in most cases, e.g.:

``` php
<?php
class Foo {}
$x = new F # Padawan suggests `Foo`
```

But shouldn't the built-in functions (like below) get completed as well?

``` php
<?php
func_g # Padawan doesn't return suggestions
func_get_args(); # same
imagecreatetruecolor(); # same
foreach(); # same
```

All I get is:

```
Padawan.php error: Could not define empty line context
```

Maybe there's something wrong with my installation process?
1. Installed `NVIM-0.1.6-dev` and `vundle`,
1. installed `deoplete`, `deoplete-padawan` and `padawan`,
1. installed `composer global require mkusher/padawan`,
1. installed `PHP 5.6.11.1` via `sudo apt-get install php`,
1. created file `foo.php`, opened it with `nvim` and started typing.

As far as I understand, the purpose of the `set omnifunc` provider is to provide language syntax completion? At least `phpcomplete-extended` was doing that... So what am I doing wrong?

[EDITED] If I install `UltiSnips` and a snippets pack I get templates suggestions, so it doesn't seem to be the problem with `deoplete`.

**Comment by mkusher** [comment]
it looks more like problem with deoplete-padawan, it doesn't send prefix. 
Cc @pbogut

**Comment by pbogut** [comment]
@mkusher, your right, prefix is not sent by the deoplete-padawan. The column is always set at the beginning of the word. I wIll take a look at this later.

@cprn, which version of padawan you are using? As far as I can tell the error is displayed on stable 0.2.1 but this version doesn't support build in functions anyway.

If you want to use omnifunc with deoplete it will take async benefits away.

It will work as expected with padawan from the master branch when I fix the issue @mkusher has addressed.

**Comment by cprn** [comment]
> which version of padawan you are using?

Whatever gets installed with `vim-plug`:

``` sh
git log --pretty=oneline
d74aad4dcfe0ce9e5f89b79f23ad92fa6b86d0d5 Update README.md
```

> It will work as expected with padawan from the master branch when I fix the issue @mkusher has addressed.

Sounds legit.

Do we close this issue and move to your github? (it says 0 open issues)

**Comment by mkusher** [comment]
@cprn yeah, it's better to continue there https://github.com/pbogut/deoplete-padawan
