### ISSUE TITLE
No response from the server.

### ISSUE THREAD

**Issue by pbogut** [mkusher/padawan.php#71]
This is somehow strange. Sometimes padawan is not responding to request at all. There is also no log message. Padawan is still up and running as a request in another file will work all right.

I can reproduce it with Laravel project.

  - `composer global require laravel/installer`
  - `laravel new test`
  - edit `vendor/laravel/framework/src/Illuminate/Database/Eloquent/Model.php`
  - There is no response from padawan-server. Well, most of the times.
  
Sometimes the server is responding, and when it does its quite fast response. I've tried it with the netcat, and it worked few times, but usually its just silent. I think it is related to [#13](https://github.com/pbogut/deoplete-padawan/issues/13).

**Comment by mwildehahn** [comment]
i think i'm seeing this issue because of the size of the file. for small files it works well, but for large files it never responds. it doesn't seem to even generate that it received the request.

**Comment by mkusher** [comment]
hm, maybe the problem is somehow connected with incorrect http body fetching.

I mean this function https://github.com/mkusher/padawan.php/blob/master/bin/padawan-server#L95

**Comment by mwildehahn** [comment]
@mkusher it should still log something before reaching that function right? i'm not seeing anything get logged

**Comment by mwildehahn** [comment]
not sure this is actually an error with the padawan-server, i feel like the request is never making it to the server.

i added some debug logging as soon as the request gets received (there already is logging that should be taking place, ie. method etc) and it never gets invoked. 

if i open up a very small file, it starts to work, open up larger file, doesn't work.

**Comment by pbogut** [comment]
I think this is a problem with `react/http`.
I've just made a quick test, and when big data is send to padawan `request` event is not triggered. So I've checked `react/http/src/Server.php` and I can see that request with small file triggers `$parser->on('headers...` but with the big one only `$parser->on('data...` is triggered.

I don't know react so I can't tell how this suppose to work exactly but clearly there is different behavior when a big file is sent and the request is not making it to the padawan.

Hope that's at least remotely clear.

**Comment by pbogut** [comment]
I think this is related to this issue: https://github.com/reactphp/http/issues/80

**Comment by mwildehahn** [comment]
that definitely sounds like the right direction

**Comment by kokx** [comment]
I can confirm that applying [the pull request](https://github.com/reactphp/http/pull/82) that solves https://github.com/reactphp/http/issues/80 will also solve these issues with padawan.php. It now works great, even in larger files!

**Comment by mkusher** [comment]
that's nice)

**Comment by halftan** [comment]
I've explained the reason at https://github.com/reactphp/http/issues/87 and there's a pending PR that fixes this https://github.com/reactphp/http/pull/82

**Comment by halftan** [comment]
Close with #91
