### ISSUE TITLE
Add --help text to padawan and padawan-server commands

### ISSUE THREAD

**Issue by kokx** [mkusher/padawan.php#75]
Currently, it is relatively hard to determine what the `padawan` and `padawan-server` commands do. It would be great to be able to pass the default `--help` flag to both commands, which would document what they do and which commands you can run on them.

**Comment by mkusher** [comment]
`padawan` command has help flag, not sure what needs to be added there

**Comment by kokx** [comment]
In that case, I am not able to trigger it however. When I pass `--help` or `help` to the `padawan` command, I get no result back.

**Comment by mkusher** [comment]
I think that's because you're on `0.2.1` branch

**Comment by kokx** [comment]
Very likely, I'm on the most recent version in composer. I'll migrate to `dev-master` then.

**Comment by kokx** [comment]
This is indeed fixed on `dev-master`.
